name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  security-check:
    name: Security Checker

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: symfonycorp/security-checker-action@v5
